ARG BASE_IMAGE=spark-agents/vllm-base:cu132
FROM ${BASE_IMAGE}

ENV VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
ENV VLLM_MARLIN_USE_ATOMIC_ADD=1
ENV VLLM_USE_FLASHINFER_MOE_FP4=0
ENV TORCH_MATMUL_PRECISION=high
ENV PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
